/*
    * Implements the regex compiler.
    * Consumes the AST generated by the parser.
    * Converts the AST into an NFA representation.
    * Handles advanced regex features like capturing groups, lookaheads, etc.
*/