#     * Contains build instructions for compiling and linking your code.
# 	  * Specifies dependencies, compiler flags, and other build configurations.
#	  * Enables you to easily compile and build your regex engine using the Make utility.